#define SIN_MAX_SKILL			241
#define SIN_MAX_USE_SKILL		21			//技能数量总数
#define SIN_MAX_SKILLBOX		21
#define SIN_MAX_SKILL_TITLE		5

#define	sinSKILL_MASK1	0xFF000000
#define	sinSKILL_MASK2	0xFFFF0000
#define	sinSKILL_MASK3	0x0000FFFF

#define SKILL_ALL_WEAPON_USE	0x11000000

#define GROUP_MECHANICIAN		0x01000000
#define GROUP_FIGHTER			0x02000000
#define GROUP_PIKEMAN			0x03000000
#define	GROUP_ARCHER			0x04000000
#define GROUP_ASSASSIN			0x09000000


#define GROUP_KNIGHT			0x05000000
#define GROUP_ATALANTA			0x06000000
#define GROUP_PRIESTESS			0x07000000
#define	GROUP_MAGICIAN			0x08000000
#define GROUP_SHAMAN			0x0A000000


#define	GROUP_OTHERSKILL		0x0B000000


#define	CHANGE_JOB1				0x00010000
#define	CHANGE_JOB2				0x00020000
#define	CHANGE_JOB3				0x00040000
#define	CHANGE_JOB4				0x00080000
#define	CHANGE_JOB5				0x00100000


#define SKILL_1					0x00000001
#define SKILL_2					0x00000002
#define SKILL_3					0x00000003
#define SKILL_4					0x00000004
#define SKILL_5					0x00000005
#define SKILL_6					0x00000006
#define SKILL_7					0x00000007
#define SKILL_8					0x00000008
#define SKILL_9					0x00000009
#define SKILL_10				0x00000010


#define SKILL_NORMAL_ATTACK     0x11111111

//机械技能

#define SKILL_EXTREME_SHIELD		(GROUP_MECHANICIAN|CHANGE_JOB1|SKILL_1) //极光护盾
#define SKILL_MECHANIC_BOMB			(GROUP_MECHANICIAN|CHANGE_JOB1|SKILL_2) //机械榴弹
#define SKILL_PHYSICAL_ABSORB		(GROUP_MECHANICIAN|CHANGE_JOB1|SKILL_3) //灵光护体
#define SKILL_POISON_ATTRIBUTE		(GROUP_MECHANICIAN|CHANGE_JOB1|SKILL_4) //毒之防御

#define SKILL_GREAT_SMASH			(GROUP_MECHANICIAN|CHANGE_JOB2|SKILL_1)
#define SKILL_MAXIMIZE				(GROUP_MECHANICIAN|CHANGE_JOB2|SKILL_2) //改良专家
#define SKILL_AUTOMATION			(GROUP_MECHANICIAN|CHANGE_JOB2|SKILL_3) //灵光飞扬
#define SKILL_SPARK					(GROUP_MECHANICIAN|CHANGE_JOB2|SKILL_4) //火花电场

#define SKILL_METAL_ARMOR			(GROUP_MECHANICIAN|CHANGE_JOB3|SKILL_1) //金属重甲
#define SKILL_GRAND_SMASH			(GROUP_MECHANICIAN|CHANGE_JOB3|SKILL_2)
#define SKILL_MECHANIC_WEAPON		(GROUP_MECHANICIAN|CHANGE_JOB3|SKILL_3)
#define SKILL_SPARK_SHIELD			(GROUP_MECHANICIAN|CHANGE_JOB3|SKILL_4) //防御电波

#define SKILL_IMPULSION				(GROUP_MECHANICIAN|CHANGE_JOB4|SKILL_1) //雷霆冲击
#define SKILL_COMPULSION			(GROUP_MECHANICIAN|CHANGE_JOB4|SKILL_2) //威慑怒吼
#define SKILL_MAGNETIC_SPHERE		(GROUP_MECHANICIAN|CHANGE_JOB4|SKILL_3) //磁性球体
#define SKILL_METAL_GOLEM			(GROUP_MECHANICIAN|CHANGE_JOB4|SKILL_4) //终极机械

#define SKILL_LANDMINNING			(GROUP_MECHANICIAN|CHANGE_JOB5|SKILL_1) //霹雳旋风
#define SKILL_H_SONIC				(GROUP_MECHANICIAN|CHANGE_JOB5|SKILL_2) //快速打击
#define SKILL_R_SMASH				(GROUP_MECHANICIAN|CHANGE_JOB5|SKILL_3) //究极之刃
#define SKILL_P_ENHENCE				(GROUP_MECHANICIAN|CHANGE_JOB5|SKILL_4) //战神祝福

//武士技能 
#define SKILL_MELEE_MASTERY			(GROUP_FIGHTER|CHANGE_JOB1|SKILL_1)
#define SKILL_FIRE_ATTRIBUTE		(GROUP_FIGHTER|CHANGE_JOB1|SKILL_2)
#define SKILL_RAVING				(GROUP_FIGHTER|CHANGE_JOB1|SKILL_3)
#define SKILL_IMPACT				(GROUP_FIGHTER|CHANGE_JOB1|SKILL_4)

#define SKILL_TRIPLE_IMPACT			(GROUP_FIGHTER|CHANGE_JOB2|SKILL_1)
#define SKILL_BRUTAL_SWING			(GROUP_FIGHTER|CHANGE_JOB2|SKILL_2)
#define SKILL_ROAR					(GROUP_FIGHTER|CHANGE_JOB2|SKILL_3) //极地怒吼
#define SKILL_RAGE_OF_ZECRAM		(GROUP_FIGHTER|CHANGE_JOB2|SKILL_4)

#define SKILL_CONCENTRATION			(GROUP_FIGHTER|CHANGE_JOB3|SKILL_1) //会心一击
#define SKILL_AVANGING_CRASH		(GROUP_FIGHTER|CHANGE_JOB3|SKILL_2)
#define SKILL_SWIFT_AXE				(GROUP_FIGHTER|CHANGE_JOB3|SKILL_3) //刺杀之斧
#define SKILL_BONE_CRASH			(GROUP_FIGHTER|CHANGE_JOB3|SKILL_4)

#define SKILL_DETORYER				(GROUP_FIGHTER|CHANGE_JOB4|SKILL_1) //破坏之击
#define SKILL_BERSERKER				(GROUP_FIGHTER|CHANGE_JOB4|SKILL_2) //疯狂怒吼
#define SKILL_CYCLONE_STRIKE		(GROUP_FIGHTER|CHANGE_JOB4|SKILL_3) //飓风袭击
#define SKILL_BOOST_HEALTH			(GROUP_FIGHTER|CHANGE_JOB4|SKILL_4)

#define SKILL_D_HIT					(GROUP_FIGHTER|CHANGE_JOB5|SKILL_1) //狂暴怒斩
#define SKILL_P_DASH				(GROUP_FIGHTER|CHANGE_JOB5|SKILL_2) //狂野冲击
#define SKILL_M_BLOW				(GROUP_FIGHTER|CHANGE_JOB5|SKILL_3) //回旋斩击
#define SKILL_B_BERSERKER			(GROUP_FIGHTER|CHANGE_JOB5|SKILL_4) //众神之怒

//枪兵技能

#define SKILL_PIKE_WIND  			(GROUP_PIKEMAN|CHANGE_JOB1|SKILL_1) //龙卷枪风
#define SKILL_ICE_ATTRIBUTE 		(GROUP_PIKEMAN|CHANGE_JOB1|SKILL_2)
#define SKILL_CRITICAL_HIT			(GROUP_PIKEMAN|CHANGE_JOB1|SKILL_3)
#define SKILL_JUMPING_CRASH			(GROUP_PIKEMAN|CHANGE_JOB1|SKILL_4)

#define SKILL_GROUND_PIKE    		(GROUP_PIKEMAN|CHANGE_JOB2|SKILL_1) //大地之枪
#define SKILL_TORNADO     			(GROUP_PIKEMAN|CHANGE_JOB2|SKILL_2) //枪之飓风
#define SKILL_WEAPONE_DEFENCE_MASTERY (GROUP_PIKEMAN|CHANGE_JOB2|SKILL_3)
#define SKILL_EXPANSION     		(GROUP_PIKEMAN|CHANGE_JOB2|SKILL_4) //无限力枪

#define SKILL_VENOM_SPEAR    		(GROUP_PIKEMAN|CHANGE_JOB3|SKILL_1) //灵蛇标枪
#define SKILL_VANISH				(GROUP_PIKEMAN|CHANGE_JOB3|SKILL_2) //隐暗之术
#define SKILL_CRITICAL_MASTERY 		(GROUP_PIKEMAN|CHANGE_JOB3|SKILL_3)
#define SKILL_CHAIN_LANCE	 		(GROUP_PIKEMAN|CHANGE_JOB3|SKILL_4)

#define SKILL_ASSASSIN_EYE    		(GROUP_PIKEMAN|CHANGE_JOB4|SKILL_1) //暗杀之眼
#define SKILL_CHARGING_STRIKE		(GROUP_PIKEMAN|CHANGE_JOB4|SKILL_2) //转换打击
#define SKILL_VAGUE			 		(GROUP_PIKEMAN|CHANGE_JOB4|SKILL_3) //影隐之遁
#define SKILL_SHADOW_MASTER	 		(GROUP_PIKEMAN|CHANGE_JOB4|SKILL_4) //宇宙幻影

#define SKILL_D_REAPER    			(GROUP_PIKEMAN|CHANGE_JOB5|SKILL_1) //回旋打击
#define SKILL_F_SPEAR				(GROUP_PIKEMAN|CHANGE_JOB5|SKILL_2) //地袭奇枪
#define SKILL_AMPLIFIED				(GROUP_PIKEMAN|CHANGE_JOB5|SKILL_3) //潜能激发
#define SKILL_SS_ATTACK		 		(GROUP_PIKEMAN|CHANGE_JOB5|SKILL_4) //旋风之枪

//弓手技能

#define SKILL_SCOUT_HAWK  			(GROUP_ARCHER|CHANGE_JOB1|SKILL_1) //侦察之鹰
#define SKILL_SHOOTING_MASTERY		(GROUP_ARCHER|CHANGE_JOB1|SKILL_2)
#define SKILL_WIND_ARROW			(GROUP_ARCHER|CHANGE_JOB1|SKILL_3)
#define SKILL_PERFECT_AIM			(GROUP_ARCHER|CHANGE_JOB1|SKILL_4)

#define SKILL_DIONS_EYE  			(GROUP_ARCHER|CHANGE_JOB2|SKILL_1)
#define SKILL_FALCON      			(GROUP_ARCHER|CHANGE_JOB2|SKILL_2) //灵魂之鹰
#define SKILL_ARROW_OF_RAGE			(GROUP_ARCHER|CHANGE_JOB2|SKILL_3)
#define SKILL_AVALANCHE       		(GROUP_ARCHER|CHANGE_JOB2|SKILL_4)

#define SKILL_ELEMENTAL_SHOT		(GROUP_ARCHER|CHANGE_JOB3|SKILL_1)
#define SKILL_GOLDEN_FALCON			(GROUP_ARCHER|CHANGE_JOB3|SKILL_2) //黄金猎鹰
#define SKILL_BOMB_SHOT    			(GROUP_ARCHER|CHANGE_JOB3|SKILL_3)
#define SKILL_PERFORATION   		(GROUP_ARCHER|CHANGE_JOB3|SKILL_4) //惯穿之箭

#define SKILL_RECALL_WOLVERIN		(GROUP_ARCHER|CHANGE_JOB4|SKILL_1) //召唤雪狼
#define SKILL_EVASION_MASTERY		(GROUP_ARCHER|CHANGE_JOB4|SKILL_2)
#define SKILL_PHOENIX_SHOT   		(GROUP_ARCHER|CHANGE_JOB4|SKILL_3) //绯凰绝炎
#define SKILL_FORCE_OF_NATURE  		(GROUP_ARCHER|CHANGE_JOB4|SKILL_4) //自然之光

#define SKILL_E_SHOT				(GROUP_ARCHER|CHANGE_JOB5|SKILL_1) //回旋之舞
#define SKILL_S_ROPE				(GROUP_ARCHER|CHANGE_JOB5|SKILL_2)
#define SKILL_N_SPLASH		   		(GROUP_ARCHER|CHANGE_JOB5|SKILL_3) //飓风之箭
#define SKILL_C_TRAP		  		(GROUP_ARCHER|CHANGE_JOB5|SKILL_4)

//游侠技能
#define SKILL_SWORD_BLAST			(GROUP_KNIGHT|CHANGE_JOB1|SKILL_1) //魔神剑
#define SKILL_HOLY_BODY				(GROUP_KNIGHT|CHANGE_JOB1|SKILL_2) //圣光护体
#define SKILL_PHYSICAL_TRANING		(GROUP_KNIGHT|CHANGE_JOB1|SKILL_3)
#define SKILL_DOUBLE_CRASH			(GROUP_KNIGHT|CHANGE_JOB1|SKILL_4)

#define SKILL_HOLY_VALOR			(GROUP_KNIGHT|CHANGE_JOB2|SKILL_1) //神力重击
#define SKILL_BRANDISH				(GROUP_KNIGHT|CHANGE_JOB2|SKILL_2) //狂躁挥舞
#define SKILL_PIERCING				(GROUP_KNIGHT|CHANGE_JOB2|SKILL_3) //一雾银
#define SKILL_DRASTIC_SPIRIT		(GROUP_KNIGHT|CHANGE_JOB2|SKILL_4) //天佑神铠

#define SKILL_SWORD_MASTERY 		(GROUP_KNIGHT|CHANGE_JOB3|SKILL_1) //精剑之术
#define SKILL_DIVINE_INHALATION		(GROUP_KNIGHT|CHANGE_JOB3|SKILL_2) //圣灵之吸
#define SKILL_HOLY_INCANTATION		(GROUP_KNIGHT|CHANGE_JOB3|SKILL_3) //圣剡之光
#define SKILL_GRAND_CROSS			(GROUP_KNIGHT|CHANGE_JOB3|SKILL_4) //圣光十字

#define SKILL_SWORD_OF_JUSTICE		(GROUP_KNIGHT|CHANGE_JOB4|SKILL_1) //真魔神剑
#define SKILL_GODLY_SHIELD			(GROUP_KNIGHT|CHANGE_JOB4|SKILL_2) //敬神之盾
#define SKILL_GOD_BLESS				(GROUP_KNIGHT|CHANGE_JOB4|SKILL_3) //上帝祝福
#define SKILL_DIVINE_PIERCING		(GROUP_KNIGHT|CHANGE_JOB4|SKILL_4) //刹剧荒舞

#define SKILL_S_BREAKER				(GROUP_KNIGHT|CHANGE_JOB5|SKILL_1)
#define SKILL_C_MOON				(GROUP_KNIGHT|CHANGE_JOB5|SKILL_2)
#define SKILL_S_BLADE				(GROUP_KNIGHT|CHANGE_JOB5|SKILL_3)
#define SKILL_H_BENEDIC				(GROUP_KNIGHT|CHANGE_JOB5|SKILL_4) //亡灵之咒

//魔枪手技能
#define SKILL_SHIELD_STRIKE			(GROUP_ATALANTA|CHANGE_JOB1|SKILL_1) //美杜莎盾
#define SKILL_FARINA				(GROUP_ATALANTA|CHANGE_JOB1|SKILL_2) //含沙射影
#define SKILL_THROWING_MASTERY		(GROUP_ATALANTA|CHANGE_JOB1|SKILL_3)
#define SKILL_VIGOR_SPEAR			(GROUP_ATALANTA|CHANGE_JOB1|SKILL_4) //精神之枪

#define SKILL_WINDY					(GROUP_ATALANTA|CHANGE_JOB2|SKILL_1) //追命劲风
#define SKILL_TWIST_JAVELIN			(GROUP_ATALANTA|CHANGE_JOB2|SKILL_2) //螺旋飞标
#define SKILL_SOUL_SUCKER			(GROUP_ATALANTA|CHANGE_JOB2|SKILL_3) //灵魂吞噬
#define SKILL_FIRE_JAVELIN			(GROUP_ATALANTA|CHANGE_JOB2|SKILL_4) //火焰烈枪

#define SKILL_SPLIT_JAVELIN			(GROUP_ATALANTA|CHANGE_JOB3|SKILL_1) //追风之枪
#define SKILL_TRIUMPH_OF_VALHALLA	(GROUP_ATALANTA|CHANGE_JOB3|SKILL_2) //战栗咆哮
#define SKILL_LIGHTNING_JAVELIN		(GROUP_ATALANTA|CHANGE_JOB3|SKILL_3) //光猎之枪
#define SKILL_STORM_JAVELIN			(GROUP_ATALANTA|CHANGE_JOB3|SKILL_4) //暴风狂标

#define SKILL_HALL_OF_VALHALLA		(GROUP_ATALANTA|CHANGE_JOB4|SKILL_1) //瓦尔哈拉之光
#define SKILL_X_RAGE				(GROUP_ATALANTA|CHANGE_JOB4|SKILL_2) //十字怒击
#define SKILL_FROST_JAVELIN			(GROUP_ATALANTA|CHANGE_JOB4|SKILL_3) //霜冻标枪
#define SKILL_VENGEANCE				(GROUP_ATALANTA|CHANGE_JOB4|SKILL_4) //狂风爆裂

#define SKILL_TALARIA				(GROUP_ATALANTA|CHANGE_JOB5|SKILL_1) //轻舞飞扬
#define SKILL_G_COUP				(GROUP_ATALANTA|CHANGE_JOB5|SKILL_2)
#define SKILL_S_ARCUDA				(GROUP_ATALANTA|CHANGE_JOB5|SKILL_3) //笨笨熊
#define SKILL_S_FEAR				(GROUP_ATALANTA|CHANGE_JOB5|SKILL_4) //火焰突袭

//祭司技能
#define SKILL_HEALING				(GROUP_PRIESTESS|CHANGE_JOB1|SKILL_1) //治愈之术
#define SKILL_HOLY_BOLT				(GROUP_PRIESTESS|CHANGE_JOB1|SKILL_2) //圣光电球
#define SKILL_MULTISPARK			(GROUP_PRIESTESS|CHANGE_JOB1|SKILL_3) //光芒四射
#define SKILL_HOLY_MIND				(GROUP_PRIESTESS|CHANGE_JOB1|SKILL_4) //意念之术

#define SKILL_MEDITATION			(GROUP_PRIESTESS|CHANGE_JOB2|SKILL_1)
#define SKILL_DIVINE_LIGHTNING		(GROUP_PRIESTESS|CHANGE_JOB2|SKILL_2) //神之雷电
#define SKILL_HOLY_REFLECTION		(GROUP_PRIESTESS|CHANGE_JOB2|SKILL_3) //神圣反射
#define SKILL_GRAND_HEALING			(GROUP_PRIESTESS|CHANGE_JOB2|SKILL_4) //圣洁之光

#define SKILL_VIGOR_BALL			(GROUP_PRIESTESS|CHANGE_JOB3|SKILL_1) //火影双重
#define SKILL_RESURRECTION			(GROUP_PRIESTESS|CHANGE_JOB3|SKILL_2) //回生之术
#define SKILL_EXTINCTION			(GROUP_PRIESTESS|CHANGE_JOB3|SKILL_3) //圣光之咒
#define SKILL_VIRTUAL_LIFE			(GROUP_PRIESTESS|CHANGE_JOB3|SKILL_4) //神圣之光

#define SKILL_GLACIAL_SPIKE			(GROUP_PRIESTESS|CHANGE_JOB4|SKILL_1) //冰霜噬月
#define SKILL_REGENERATION_FIELD	(GROUP_PRIESTESS|CHANGE_JOB4|SKILL_2) //再生领域
#define SKILL_CHAIN_LIGHTNING		(GROUP_PRIESTESS|CHANGE_JOB4|SKILL_3) //天雷之怒
#define SKILL_SUMMON_MUSPELL		(GROUP_PRIESTESS|CHANGE_JOB4|SKILL_4) //神圣天使

#define SKILL_S_IMPACT				(GROUP_PRIESTESS|CHANGE_JOB5|SKILL_1)
#define SKILL_P_ICE					(GROUP_PRIESTESS|CHANGE_JOB5|SKILL_2)
#define SKILL_S_PRMIEL				(GROUP_PRIESTESS|CHANGE_JOB5|SKILL_3) //光明天使
#define SKILL_B_KRISHNA				(GROUP_PRIESTESS|CHANGE_JOB5|SKILL_4) //仙女散花

//魔法师技能
#define SKILL_AGONY					(GROUP_MAGICIAN|CHANGE_JOB1|SKILL_1) //魔力转化
#define SKILL_FIRE_BOLT				(GROUP_MAGICIAN|CHANGE_JOB1|SKILL_2) //火箭之术
#define SKILL_ZENITH				(GROUP_MAGICIAN|CHANGE_JOB1|SKILL_3) //集合之术
#define SKILL_FIRE_BALL				(GROUP_MAGICIAN|CHANGE_JOB1|SKILL_4) //火球之术

#define SKILL_MENTAL_MASTERY		(GROUP_MAGICIAN|CHANGE_JOB2|SKILL_1)
#define SKILL_WATORNADO				(GROUP_MAGICIAN|CHANGE_JOB2|SKILL_2) //龙卷海风
#define SKILL_ENCHANT_WEAPON		(GROUP_MAGICIAN|CHANGE_JOB2|SKILL_3) //元素之术
#define SKILL_DEAD_RAY				(GROUP_MAGICIAN|CHANGE_JOB2|SKILL_4) //冥亡之光

#define SKILL_ENERGY_SHIELD			(GROUP_MAGICIAN|CHANGE_JOB3|SKILL_1) //魔法守护
#define SKILL_DIASTROPHISM			(GROUP_MAGICIAN|CHANGE_JOB3|SKILL_2) //地裂冲击
#define SKILL_SPIRIT_ELEMENTAL		(GROUP_MAGICIAN|CHANGE_JOB3|SKILL_3) //灵魂召唤
#define SKILL_DANCING_SWORD			(GROUP_MAGICIAN|CHANGE_JOB3|SKILL_4) //元素之剑

#define SKILL_FIRE_ELEMENTAL		(GROUP_MAGICIAN|CHANGE_JOB4|SKILL_1) //伊夫列特
#define SKILL_FLAME_WAVE			(GROUP_MAGICIAN|CHANGE_JOB4|SKILL_2) //火焰波动
#define SKILL_DISTORTION			(GROUP_MAGICIAN|CHANGE_JOB4|SKILL_3) //空间扭曲
#define SKILL_M_METEO				(GROUP_MAGICIAN|CHANGE_JOB4|SKILL_4) //陨石召唤

#define SKILL_SILRAPHIM				(GROUP_MAGICIAN|CHANGE_JOB5|SKILL_1) //流星火雨
#define SKILL_V_TENUS				(GROUP_MAGICIAN|CHANGE_JOB5|SKILL_2)
#define SKILL_P_IGNIS				(GROUP_MAGICIAN|CHANGE_JOB5|SKILL_3)
#define SKILL_T_ANIMA				(GROUP_MAGICIAN|CHANGE_JOB5|SKILL_4) //圣光法阵

// 刺客技能
#define SKILL_STRINGER				(GROUP_ASSASSIN|CHANGE_JOB1|SKILL_1) //刺击
#define SKILL_RUNNING_HIT			(GROUP_ASSASSIN|CHANGE_JOB1|SKILL_2) //闪击
#define SKILL_SWORDMASTERY			(GROUP_ASSASSIN|CHANGE_JOB1|SKILL_3) //强化攻击
#define SKILL_WISP					(GROUP_ASSASSIN|CHANGE_JOB1|SKILL_4) //弱点攻击

#define SKILL_VENOM_THORN			(GROUP_ASSASSIN|CHANGE_JOB2|SKILL_1) //毒牙连击
#define SKILL_ALAS					(GROUP_ASSASSIN|CHANGE_JOB2|SKILL_2) //敏捷之力
#define SKILL_SOUL_SHOCK			(GROUP_ASSASSIN|CHANGE_JOB2|SKILL_3) //灵魂震撼
#define SKILL_ATTACK_MASTERY		(GROUP_ASSASSIN|CHANGE_JOB2|SKILL_4) //攻击大师

#define SKILL_SORE_SWORD			(GROUP_ASSASSIN|CHANGE_JOB3|SKILL_1) //飞剑之舞
#define SKILL_BEAT_UP				(GROUP_ASSASSIN|CHANGE_JOB3|SKILL_2) //跳斩
#define SKILL_INPES					(GROUP_ASSASSIN|CHANGE_JOB3|SKILL_3) //敏捷大师
#define SKILL_BLIND					(GROUP_ASSASSIN|CHANGE_JOB3|SKILL_4) //致盲

#define SKILL_FROST_WIND			(GROUP_ASSASSIN|CHANGE_JOB4|SKILL_1) //冰冻之刃
#define SKILL_FATAL_MASTERY			(GROUP_ASSASSIN|CHANGE_JOB4|SKILL_2) //致命艺术
#define SKILL_POLLUTED				(GROUP_ASSASSIN|CHANGE_JOB4|SKILL_3) //瘟疫之刃
#define SKILL_PASTING_SHADOW		(GROUP_ASSASSIN|CHANGE_JOB4|SKILL_4) //影子闪击

#define SKILL_SHADOW_BOMB			(GROUP_ASSASSIN|CHANGE_JOB5|SKILL_1) //影子火焰
#define SKILL_RISING_SHASH			(GROUP_ASSASSIN|CHANGE_JOB5|SKILL_2) //地裂斩
#define SKILL_VIOLENCE_STAB			(GROUP_ASSASSIN|CHANGE_JOB5|SKILL_3) //猛龙摆尾
#define SKILL_STORM					(GROUP_ASSASSIN|CHANGE_JOB5|SKILL_4) //风暴之刃

//萨满技能

#define SKILL_DARK_BOLT				(GROUP_SHAMAN|CHANGE_JOB1|SKILL_1) //暗黑闪电
#define SKILL_DARK_WAVE				(GROUP_SHAMAN|CHANGE_JOB1|SKILL_2) //暗黑波浪
#define SKILL_CURSE_LAZY			(GROUP_SHAMAN|CHANGE_JOB1|SKILL_3) //诅咒雷击
#define SKILL_INNER_PEACE			(GROUP_SHAMAN|CHANGE_JOB1|SKILL_4) //内心平和

#define SKILL_SPIRITUAL_FLARE		(GROUP_SHAMAN|CHANGE_JOB2|SKILL_1) //精神咒术
#define SKILL_SPIRITUAL_MANACLE		(GROUP_SHAMAN|CHANGE_JOB2|SKILL_2) //灵魂枷锁
#define SKILL_CHASING_HUNT			(GROUP_SHAMAN|CHANGE_JOB2|SKILL_3) //猎取
#define SKILL_ADVENT_MIGAL			(GROUP_SHAMAN|CHANGE_JOB2|SKILL_4) //迈克尔

#define SKILL_RAIN_MAKER			(GROUP_SHAMAN|CHANGE_JOB3|SKILL_1) //祈雨师
#define SKILL_LAND_OF_GHOST			(GROUP_SHAMAN|CHANGE_JOB3|SKILL_2) //陆地灵魂
#define SKILL_HAUNT					(GROUP_SHAMAN|CHANGE_JOB3|SKILL_3) //鬼混重回
#define SKILL_SCRATCH				(GROUP_SHAMAN|CHANGE_JOB3|SKILL_4) //抓破

#define SKILL_RECALL_BLOODYKNIGHT	(GROUP_SHAMAN|CHANGE_JOB4|SKILL_1) //嗜血之夜
#define SKILL_JUDGEMENT				(GROUP_SHAMAN|CHANGE_JOB4|SKILL_2) //审判
#define SKILL_ADVENT_MIDRANDA		(GROUP_SHAMAN|CHANGE_JOB4|SKILL_3) //米德兰达
#define SKILL_MOURNING_OF_PRAY		(GROUP_SHAMAN|CHANGE_JOB4|SKILL_4) //旭日东升

#define SKILL_CREED					(GROUP_SHAMAN|CHANGE_JOB5|SKILL_1) //咒术信仰
#define SKILL_PRESS_OF_DEITY		(GROUP_SHAMAN|CHANGE_JOB5|SKILL_2) //诅咒之力
#define SKILL_CHOSTY_NAIL			(GROUP_SHAMAN|CHANGE_JOB5|SKILL_3) //死亡之爪
#define SKILL_HIGH_REGENERATION		(GROUP_SHAMAN|CHANGE_JOB5|SKILL_4) //高级再升

	
#define SKILL_FORCE_ORB				(GROUP_OTHERSKILL|CHANGE_JOB1|SKILL_1)
#define CHANGE_JOB3_QUEST			(GROUP_OTHERSKILL|CHANGE_JOB1|SKILL_2)
#define CHANGE_ELEMENTARY_QUEST		(GROUP_OTHERSKILL|CHANGE_JOB1|SKILL_3)
	
#define CLANSKILL_ABSORB			(GROUP_OTHERSKILL|CHANGE_JOB1|SKILL_4)
#define CLANSKILL_ATTACK			(GROUP_OTHERSKILL|CHANGE_JOB1|SKILL_5)
#define CLANSKILL_EVASION			(GROUP_OTHERSKILL|CHANGE_JOB1|SKILL_6)

#define BOOSTER_ITEM_LIFE			(GROUP_OTHERSKILL|CHANGE_JOB1|SKILL_7)
#define BOOSTER_ITEM_MANA			(GROUP_OTHERSKILL|CHANGE_JOB1|SKILL_8)
#define BOOSTER_ITEM_STAMINA		(GROUP_OTHERSKILL|CHANGE_JOB1|SKILL_9)

#define SKILLDELAY_ITEM_LIFE		(GROUP_OTHERSKILL|CHANGE_JOB2|SKILL_1)

	
#define SCROLL_INVULNERABILITY		(GROUP_OTHERSKILL|CHANGE_JOB2|SKILL_1)
#define SCROLL_CRITICAL				(GROUP_OTHERSKILL|CHANGE_JOB2|SKILL_2)
#define SCROLL_EVASION				(GROUP_OTHERSKILL|CHANGE_JOB2|SKILL_3)

#define STONE_R_FIRECRYTAL			(GROUP_OTHERSKILL|CHANGE_JOB2|SKILL_4)
#define STONE_R_ICECRYTAL			(GROUP_OTHERSKILL|CHANGE_JOB2|SKILL_5)
#define STONE_R_LINGHTINGCRYTAL		(GROUP_OTHERSKILL|CHANGE_JOB2|SKILL_6)

#define STONE_A_FIGHTER				(GROUP_OTHERSKILL|CHANGE_JOB3|SKILL_1)
#define STONE_A_MECHANICIAN			(GROUP_OTHERSKILL|CHANGE_JOB3|SKILL_2)
#define STONE_A_PIKEMAN				(GROUP_OTHERSKILL|CHANGE_JOB3|SKILL_3)
#define STONE_A_ARCHER				(GROUP_OTHERSKILL|CHANGE_JOB3|SKILL_4)

#define STONE_A_KNIGHT				(GROUP_OTHERSKILL|CHANGE_JOB3|SKILL_5)
#define STONE_A_ATALANTA			(GROUP_OTHERSKILL|CHANGE_JOB3|SKILL_6)
#define STONE_A_MAGICIAN			(GROUP_OTHERSKILL|CHANGE_JOB3|SKILL_7)
#define STONE_A_PRIESTESS			(GROUP_OTHERSKILL|CHANGE_JOB3|SKILL_8)
#define STONE_A_ASSASSIN			(GROUP_OTHERSKILL|CHANGE_JOB3|SKILL_9)
#define STONE_A_SAMAN				(GROUP_OTHERSKILL|CHANGE_JOB3|SKILL_10)

#define SCROLL_P_INVULNERABILITY    (GROUP_OTHERSKILL|CHANGE_JOB4|SKILL_1)
#define SCROLL_P_CRITICAL		    (GROUP_OTHERSKILL|CHANGE_JOB4|SKILL_2)
#define SCROLL_P_EVASION		    (GROUP_OTHERSKILL|CHANGE_JOB4|SKILL_3)

#define SKILL_CRYSTAL_ORB			(GROUP_OTHERSKILL|CHANGE_JOB5|SKILL_1)
#define SKILL_WARNING_TIME			(GROUP_OTHERSKILL|CHANGE_JOB5|SKILL_2)
#define SKILL_WING_EFFECT			(GROUP_OTHERSKILL|CHANGE_JOB5|SKILL_3)



struct sSKILL_INFO
{
	char SkillName[64];
	char SkillDoc[150];
	int  RequireLevel;
	int  UseStamina[2];
	int	 RequireMastery[2];
	int  Element[3];
	DWORD UseWeaponCode[10];
	int (*FuncPointer)();
	DWORD	CODE;
	DWORD   USECODE;
	int *UseMana;

	int     SkillNum;
};
struct sSKILLBOX
{ 
	RECT BoxRect;
	RECT GageRect;

};
struct sSKILL
{  
	char	sSkillName[32];
	DWORD	CODE;
	char    FileName[32];
	char    IconName[32];
	int     Flag;
	int     Use;
	int     Point;
	int     ShortKey;
	int     MousePosi;
	int     Position;
	int     UseTime;
	int     CheckTime;
	int     GageLength;
	int     GageLength2;
	int     Mastery;
	int     UseSKillIncreCount;
	int     UseSkillCount;
	int 	UseSkillMastery;
	int     UseSkillMasteryGage;
	int     UseSkillFlag;
	int     PlusState[5];
	int		Time[2];
	int		PartyFlag;
	int     ElementIndex;
	int     MatIcon;

	DWORD	PlayTime;
	int		dwObjectSerial;
	int     IconAlpha;
	int     IconPosiX;
	int     IconTime;
	int     IconFlag;

	int		SkillCodeIndex;

	DWORD   SkillTaget_CODE;
	int     SummonFlag;

	sSKILL_INFO Skill_Info;
};
struct sUSESKILL
{
	sSKILL UseSkill[SIN_MAX_USE_SKILL];
	sSKILLBOX SkillBox[SIN_MAX_USE_SKILL];
	sSKILL *pLeftSkill;		
	sSKILL *pRightSkill;
	int   SkillPoint;
	int   SkillPoint4;

};

struct sPASSIVE_INFO
{
	int Flag;
	float DamagePercent;
	DWORD UseWeaponCode[10];
	DWORD CODE;


};
struct sSKILLPASSIVE
{
	sPASSIVE_INFO sPassive_Info[10];
	int Resistance[8];

};

class cSKILL
{

public:

	int OpenFlag;

	int MatSkill[4];
	DWORD UseSkillBox; 

	int CheckMasteryData[SIN_MAX_USE_SKILL];
	int CheckSkillPointData[SIN_MAX_USE_SKILL];
	int CheckSkillMasteyData[SIN_MAX_USE_SKILL];

	smTEXTUREHANDLE  *lpSkillMain;
	smTEXTUREHANDLE  *lpSkillMain2;
	smTEXTUREHANDLE  *lpSkillMainLeftB;
	smTEXTUREHANDLE  *lpSkillMainRightB;
	smTEXTUREHANDLE  *lpSkillGage[2];
	smTEXTUREHANDLE  *lpSkillGage2[2];
	smTEXTUREHANDLE  *lpSkillGage3;
	smTEXTUREHANDLE  *lpSkillGage4;
	smTEXTUREHANDLE  *lpSkillGage5;
	smTEXTUREHANDLE  *lpSkillTitle[SIN_MAX_SKILL_TITLE];
	smTEXTUREHANDLE  *lpSkillButton_Gray[SIN_MAX_USE_SKILL];
	smTEXTUREHANDLE  *lpSkillButton[SIN_MAX_USE_SKILL];
	smTEXTUREHANDLE  *lpSelectSkill;
	smTEXTUREHANDLE  *lpShortKey[8];
	smTEXTUREHANDLE  *lpSkillBoxBack;
	smTEXTUREHANDLE  *lpWeaponIcon[12];
	smTEXTUREHANDLE  *lpMasteryInfo;
	smTEXTUREHANDLE  *lpSkillDown;

public:
	cSKILL();
	~cSKILL();
};

extern cSKILL	cSkill;
extern sUSESKILL sinSkill;
extern sSKILL_INFO sSkill_Info[SIN_MAX_SKILL];
extern sSKILLBOX sLeftRightSkill[2];
extern sSKILL  *pUseSkill;

extern sSKILL  ContinueSkill[10];
extern sSKILLPASSIVE sSkillPassive;

extern sSKILL sSkill[SIN_MAX_SKILL];

extern int SelectInterSkill;

extern int     SkillInfoShowFlag;
extern POINT	SkillInfoBoxPosi;
extern POINT   SkillInfoTextPosi;
extern POINT   SkillBoxSize;
extern char    szSkillInfoBuff[5000];

extern int     SkillDocLineCnt[6];
extern int     NextSkillLevelLine;

extern sSKILL *pMasterSkill;
extern int  SkillMasterFlag;

extern int ShowSkillUpInfo;

extern int  SkillMasterOkFlag[2];

extern int   SkillIconIndex[10];
extern POINT SkillIconPosi;
extern int   SkillInconCnt;

extern int TestSkillDelayTime[16];

extern int ChangeJobSkillPlus;

extern POINT SkillUpInfo;
extern POINT SkillUpInfoPosi;

extern int ShowSkillClose;

extern DWORD ClearSkillCODE;

extern int ContinueSkillCancelFlag;

extern int SetT_Of_ValhallaFlag;
extern int SetT_Of_ValhallaFlag2;
extern int SetT_Of_ValhallaLV;
extern int SetH_Of_ValhallaLV;
extern int SetT_Of_ValhallaPOINT;

extern int AddVirtualLife[2];
extern int sinVirtualLifeTime;
extern int sinVirtualLifePercent;

extern int AddBoosterLife;
extern int BoosterLifeTime;
extern int BoosterLifePercent;
extern int LifeFlag;
extern short tempLife[];

extern int AddVirtualMana[2];
extern int sinVirtualManaTime;
extern int sinVirtualManaPercent;
extern int ManaFlag;
extern short tempMana[];

extern int AddVirtualStamina[2];
extern int sinVirtualStaminaTime;
extern int sinVirtualStaminaPercent;
extern int StaminaFlag;
extern short tempStamina[];

extern int Mat_BoosterItem[];

extern int MatForceOrb[];
extern int MatQuestTimer;
extern int MatWarning;

//extern int MatCrystalOrb[MAX_CRYSTAL];

extern int MatBillingMagicForceOrb[];

extern int SkillButtonIndex;
extern int Skill4ButtonIndex;

extern int ContinueSkillMouseIndex;
extern sSKILL  TempContinueSkill[10]; 

extern int nMat_SkillDelayItem[];
extern int sinAddSkillDelay;
extern int sinSkillDelayTime; 
extern int SkillDelayFlag;