#include "StdAfx.h"
#include "color3.h"

const color3 color3::Black(0.f, 0.f, 0.f);
const color3 color3::Gray(0.5f, 0.5f, 0.5f);
const color3 color3::White(1.f, 1.f, 1.f);
const color3 color3::Red(1.f, 0.f, 0.f);
const color3 color3::Green(0.f, 1.f, 0.f);
const color3 color3::Blue(0.f, 0.f, 1.f);
const color3 color3::Magenta(1.f, 0.f, 1.f);
const color3 color3::Cyan(0.f, 1.f, 1.f);
const color3 color3::Yellow(1.f, 1.f, 0.f);
